language: java
before_install:
- curl https://raw.github.com/liveSense/all/master/travis-settings.xml --create-dirs
  -o target/travis/settings.xml
jdk:
- openjdk6
script:
- mvn deploy --settings target/travis/settings.xml
env:
  global:
  - secure: 0TtDNPEc9UBB+oICnBuB3j6NPCiLQPsZqMgJ/kNEsppPPMfGj8+0Tr0pW+VZwiSua48nI3kCaa0HdGJNvWFqlRJ7ZUIFAVFN0v1la4ElW4Iorru2ZeVnTltxDpnMdRKmLUUtDMZjPACHmCOJ6yjH85wMcuXGqOmJ0nqn7Kk0CuE=
  - secure: zwc1zUDNV3IxDXuFyXkDSvW7cv5YBR9PMst6EI7mPRX69ouBy2y9d/PrjL2gf8e5nk5VYhdV/nvedDk76x7qRjyiiNMsac2yT6EgbEHxXAbmHdAZGuMngCmycIwQ5peu2iRJZSi1N7Y7qAlmAMb7rnlFdDtiSLysqbV1wNPUwHE=
